package br.jus.tjrs.cronos.app.exception;

import br.jus.tjrs.cronos.core.CronosException;
import br.jus.tjrs.cronos.core.messages.MessageKey;

public enum CronosErrors implements MessageKey
{
   DADOS_SALVOS_SUCESSO_000,
   FALHA_LOGIN_001,
   FALHA_SOLICITACAO_002,
   USUARIO_INVALIDO_003,
   USUARIO_INEXISTENTE_004,
   USUARIO_SEM_PERMISSAO_005,
   USUARIO_SENHA_OBRIGATORIOS_006,
   PERFIL_INEXISTENTE_007,
   USUARIO_INATIVO_008,
   FALHA_OPERACAO_009,
   CONFIRMAR_EXCLUSAO_010,
   FALHA_CRIACAO_GRUPO_TRABALHO_011,
   GRUPO_TRABALHO_INEXISTENTE_012,
   REGISTROS_NAO_ENCONTADOS_013,
   PESQUISA_MINIMA_014,
   PESQUISA_VAZIA_015,
   USUARIO_NAO_SELECIONADO_INCLUSAO_016,
   CAMPOS_OBRIGATORIOS_TOPICO_017,
   ELEMENTOS_OBRIGATORIOS_018,
   ELEMENTOS_OBRIGATORIOS_019,
   ICONES_OBRIGATORIOS_020,
   ICONES_TAMANHO_MAXIMO_021,
   REGISTROS_DUPLICADOS_022,
   REGISTROS_CONCORRENTES_023,
   FALHA_SOLICITACAO_024,
   CAMPO_OBRIGATORIO_026,
   ELEMENTOS_OBRIGATORIOS_027,
   CAMPO_TAMANHO_MINIMO_028,
   CAMPO_TAMANHO_MAXIMO_029,
   CAMPO_TAMANHO_EXATO_030,
   UNSUPPORTED_OPERATION_031;

   public String getName()
   {
      return name();
   }

   public CronosException create()
   {
      return new CronosException(this);
   }

   public CronosException create(String... args)
   {
      return new CronosException(this, args);
   }
}
