/*
Script gerado por Aqua Data Studio 7.0.22 em Out-21-2015 05:18:48 PM
Banco de Dados: XE
Esquema: JAGUAR
Objetos: TABLE, VIEW, SYNONYM, SEQUENCE, PACKAGE, PACKAGE_BODY, PROCEDURE, FUNCTION, OBJECT_TYPE, TABLE_TYPE, ARRAY_TYPE, CLUSTER
*/
DROP SEQUENCE SE_UNIDADEFEDERATIVA;
DROP SEQUENCE SE_DEPARTAMENTO;
DROP TABLE UNIDADEFEDERATIVA;
DROP TABLE DEPARTAMENTO;

CREATE TABLE DEPARTAMENTO ( 
	"PK_DEPARTAMENTO"     	NUMBER(10,0) NOT NULL,
	"DT_ULT_ALTERACAO"    	TIMESTAMP(6) NULL,
	"DATA_CRIACAO"        	TIMESTAMP(6) NULL,
	"DESCRICAO"           	VARCHAR2(100) NULL,
	"IN_SITUACAO_REGISTRO"	VARCHAR2(1) NOT NULL,
	"NM_ULT_ALTERACAO"    	VARCHAR2(150) NULL,
	"VERSAO_REGISTRO"     	NUMBER(10,0) NULL,
	"ID_DEPARTAMENTO_PAI" 	NUMBER(10,0) NULL,
	PRIMARY KEY("PK_DEPARTAMENTO")
	NOT DEFERRABLE
	 VALIDATE
);
CREATE TABLE UNIDADEFEDERATIVA ( 
	"PK_UNIDADEFEDERATIVA"	NUMBER(19,0) NOT NULL,
	"DT_ULT_ALTERACAO"    	TIMESTAMP(6) NULL,
	"DATA_CRIACAO"        	TIMESTAMP(6) NULL,
	"NOME"                	VARCHAR2(100) NULL,
	"SIGLA"               	VARCHAR2(60) NULL,
	"IN_SITUACAO_REGISTRO"	VARCHAR2(1) NOT NULL,
	"NM_ULT_ALTERACAO"    	VARCHAR2(150) NULL,
	"VERSAO_REGISTRO"     	NUMBER(10,0) NULL,
	PRIMARY KEY("PK_UNIDADEFEDERATIVA")
	NOT DEFERRABLE
	 VALIDATE
);
CREATE SEQUENCE SE_DEPARTAMENTO
	INCREMENT BY 1
	START WITH 21
	MAXVALUE 9999999999999999999999999999
	NOMINVALUE
	NOCYCLE
	CACHE 20
	NOORDER;
CREATE SEQUENCE SE_UNIDADEFEDERATIVA
	INCREMENT BY 1
	START WITH 1
	MAXVALUE 9999999999999999999999999999
	NOMINVALUE
	NOCYCLE
	CACHE 20
	NOORDER;
	


CREATE TABLE CURRICULO_CONTEUDO (PK_CURRICULO_CONTEUDO NUMBER(10) NOT NULL, CONTEUDO_BINARIO BLOB NULL, DT_ULT_ALTERACAO TIMESTAMP NULL, DATA_CRIACAO TIMESTAMP NULL, IN_SITUACAO_REGISTRO VARCHAR2(1) NOT NULL, NM_ULT_ALTERACAO VARCHAR2(150) NULL, VERSAO_REGISTRO NUMBER(10) NULL, PRIMARY KEY (PK_CURRICULO_CONTEUDO));


CREATE TABLE CURRICULO (PK_CURRICULO NUMBER(10) NOT NULL, DT_ULT_ALTERACAO TIMESTAMP NULL, DATA_CRIACAO TIMESTAMP NULL, NOME VARCHAR2(255) NULL, IN_SITUACAO_REGISTRO VARCHAR2(1) NOT NULL, TAMANHO NUMBER(10) NULL, TIPO VARCHAR2(255) NULL, URL VARCHAR2(255) NULL, NM_ULT_ALTERACAO VARCHAR2(150) NULL, VERSAO_REGISTRO NUMBER(10) NULL, CONTEUDO_PK_CURRICULO_CONTEUDO NUMBER(10) NULL, PRIMARY KEY (PK_CURRICULO));

CREATE TABLE DEPENDENTE (ID NUMBER(5) NOT NULL, DT_ULT_ALTERACAO TIMESTAMP NULL, DATA_CRIACAO TIMESTAMP NULL, NOME VARCHAR2(255) NULL, SEXO VARCHAR2(1) NULL, IN_SITUACAO_REGISTRO VARCHAR2(1) NOT NULL, NM_ULT_ALTERACAO VARCHAR2(150) NULL, VERSAO_REGISTRO NUMBER(10) NULL, FUNCIONARIO_ID NUMBER(5) NULL, PRIMARY KEY (ID));

CREATE TABLE FOTO_CONTEUDO (PK_FOTO_CONTEUDO NUMBER(10) NOT NULL, CONTEUDO_BINARIO BLOB NULL, DT_ULT_ALTERACAO TIMESTAMP NULL, DATA_CRIACAO TIMESTAMP NULL, IN_SITUACAO_REGISTRO VARCHAR2(1) NOT NULL, NM_ULT_ALTERACAO VARCHAR2(150) NULL, VERSAO_REGISTRO NUMBER(10) NULL, PRIMARY KEY (PK_FOTO_CONTEUDO));

CREATE TABLE FOTO (PK_FOTO NUMBER(10) NOT NULL, DT_ULT_ALTERACAO TIMESTAMP NULL, DATA_CRIACAO TIMESTAMP NULL, NOME VARCHAR2(255) NULL, IN_SITUACAO_REGISTRO VARCHAR2(1) NOT NULL, TAMANHO NUMBER(10) NULL, TIPO VARCHAR2(255) NULL, URL VARCHAR2(255) NULL, NM_ULT_ALTERACAO VARCHAR2(150) NULL, VERSAO_REGISTRO NUMBER(10) NULL, CONTEUDO_PK_CURRICULO_CONTEUDO NUMBER(10) NULL, PRIMARY KEY (PK_FOTO));

CREATE TABLE FUNCIONARIO (ID NUMBER(5) NOT NULL, CPF VARCHAR2(255) NULL, DT_ULT_ALTERACAO TIMESTAMP NULL, DATA_CRIACAO TIMESTAMP NULL, DATANASCIMENTO DATE NULL, EMAIL VARCHAR2(255) NULL, ESTADOCIVIL VARCHAR2(1) NULL, NOME VARCHAR2(255) NULL, OBSERVACAO VARCHAR2(255) NULL, SEXO VARCHAR2(1) NULL, SITHISTORICOPLC VARCHAR2(255) NULL, IN_SITUACAO_REGISTRO VARCHAR2(1) NOT NULL, TEMCURSOSUPERIOR NUMBER(1) default 0 NULL, NM_ULT_ALTERACAO VARCHAR2(150) NULL, VERSAO_REGISTRO NUMBER(10) NULL, DEPARTAMENTO_PK_DEPARTAMENTO NUMBER(10) NULL, ID_FOTO NUMBER(10) NULL, PRIMARY KEY (ID));

CREATE TABLE HISTORICO_PROFISSIONAL (ID NUMBER(5) NOT NULL, DT_ULT_ALTERACAO TIMESTAMP NULL, DATA_CRIACAO TIMESTAMP NULL, DATAINICIO DATE NULL, DESCRICAO VARCHAR2(255) NULL, SALARIO NUMBER(11) NULL, IN_SITUACAO_REGISTRO VARCHAR2(1) NOT NULL, NM_ULT_ALTERACAO VARCHAR2(150) NULL, VERSAO_REGISTRO NUMBER(10) NULL, FUNCIONARIO_ID NUMBER(5) NULL, PRIMARY KEY (ID));

CREATE TABLE FUNCIONARIO_CURRICULO (FuncionarioEntity_ID NUMBER(5) NOT NULL, curriculo_PK_CURRICULO NUMBER(10) NOT NULL, PRIMARY KEY (FuncionarioEntity_ID, curriculo_PK_CURRICULO));

ALTER TABLE CURRICULO ADD CONSTRAINT CRRCLOCNTDOPKCURRICULOCONTEUDO FOREIGN KEY (CONTEUDO_PK_CURRICULO_CONTEUDO) REFERENCES CURRICULO_CONTEUDO (PK_CURRICULO_CONTEUDO);

ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_FUNCIONARIO_ID FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID);

ALTER TABLE FOTO ADD CONSTRAINT FTOCONTEUDOPKCURRICULOCONTEUDO FOREIGN KEY (CONTEUDO_PK_CURRICULO_CONTEUDO) REFERENCES CURRICULO_CONTEUDO (PK_CURRICULO_CONTEUDO);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_ID_FOTO FOREIGN KEY (ID_FOTO) REFERENCES FOTO (PK_FOTO);

ALTER TABLE HISTORICO_PROFISSIONAL ADD CONSTRAINT HSTRICOPROFISSIONALFNCONARIOID FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID);

ALTER TABLE FUNCIONARIO_CURRICULO ADD CONSTRAINT FNCNRCURRICULOcrrclPKCURRICULO FOREIGN KEY (curriculo_PK_CURRICULO) REFERENCES CURRICULO (PK_CURRICULO);

SELECT SE_CURRICULO.NEXTVAL FROM DUAL;

CREATE SEQUENCE SE_CURRICULO INCREMENT BY 50 START WITH 50;

SELECT SE_FOTO.NEXTVAL FROM DUAL;

CREATE SEQUENCE SE_FOTO INCREMENT BY 50 START WITH 50;

ALTER SEQUENCE SE_UNIDADEFEDERATIVA INCREMENT BY 1;

SELECT SE_FUNCIONARIO.NEXTVAL FROM DUAL;

CREATE SEQUENCE SE_FUNCIONARIO INCREMENT BY 50 START WITH 50;

SELECT SE_CURRICULO_CONTEUDO.NEXTVAL FROM DUAL;

CREATE SEQUENCE SE_CURRICULO_CONTEUDO INCREMENT BY 50 START WITH 50;

SELECT SE_HISTORICO_PROFISSIONAL.NEXTVAL FROM DUAL;

CREATE SEQUENCE SE_HISTORICO_PROFISSIONAL INCREMENT BY 50 START WITH 50;

ALTER SEQUENCE SE_DEPARTAMENTO INCREMENT BY 1;

SELECT SE_FOTO_CONTEUDO.NEXTVAL FROM DUAL;

CREATE SEQUENCE SE_FOTO_CONTEUDO INCREMENT BY 50 START WITH 50;

SELECT SE_DEPENDENTE.NEXTVAL FROM DUAL;

CREATE SEQUENCE SE_DEPENDENTE INCREMENT BY 50 START WITH 50;

ALTER SEQUENCE SE_DEPARTAMENTO INCREMENT BY 1;

ALTER SEQUENCE SE_HISTORICO_PROFISSIONAL INCREMENT BY 50;

ALTER SEQUENCE SE_CURRICULO INCREMENT BY 50;

ALTER SEQUENCE SE_FUNCIONARIO INCREMENT BY 50;

ALTER SEQUENCE SE_CURRICULO_CONTEUDO INCREMENT BY 50;

ALTER SEQUENCE SE_DEPENDENTE INCREMENT BY 50;

ALTER SEQUENCE SE_FOTO INCREMENT BY 50;

ALTER SEQUENCE SE_FOTO_CONTEUDO INCREMENT BY 50;

ALTER SEQUENCE SE_UNIDADEFEDERATIVA INCREMENT BY 1;
	
